tasks:
  - name: conda venv
    init: |
      wget https://repo.anaconda.com/miniconda/Miniconda3-py39_22.11.1-1-Linux-x86_64.sh -O ~/miniconda.sh
      bash ~/miniconda.sh -b -p
      rm ~/miniconda.sh
      source $HOME/miniconda3/bin/activate
      conda env create -f conda.yml
    command: conda activate venv

vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-python.black-formatter
    - ms-python.isort
    - ms-toolsai.jupyter
    - ms-toolsai.vscode-jupyter-cell-tags
    - streetsidesoftware.code-spell-checker
    - eamodio.gitlens
    - yzhang.markdown-all-in-one